### ISSUE TITLE
Phase 01

### ISSUE THREAD

**Issue by tjsg1992** [tjsg1992/Compiler-Project#3]
~~Exercise 2.10. Modify Scanner in the j-- compiler to scan (and ignore) Java multi-line
comments.~~

~~Exercise 2.11. Modify Scanner in the j-- compiler to recognize and return all Java operators
that are not reserved words.~~

~~Exercise 2.12. Modify Scanner in the j-- compiler to recognize and return all Java reserved
words.~~

~~Exercise 2.13. Modify Scanner in the j-- compiler to recognize and return Java doubleprecision
literals (returned as DOUBLE_LITERAL).~~

~~Exercise 2.14. Modify Scanner in the j-- compiler to recognize and return all other literals
in Java, for example, FLOAT_LITERAL, LONG_LITERAL, etc.~~

~~(Bonus) Exercise 2.15. Modify Scanner in the j-- compiler to recognize and return all other
representations of integers (hexadecimal, octal, etc.).~~

**Comment by tjsg1992** [comment]
If we did want to make issues for each of these after all, I certainly wouldn't be opposed to it. It's also just going to be a pain.

**Comment by cresse** [comment]
i dont know the specific syntax for indicating an empty string, but how's this?
FLOAT_LITERAL ::= "0" | ("1"-"9") {"0"-"9"} (""|".") ("1"-"9") {"0"-"9"} (""|"e"|"E") ("1"-"9") {"0"-"9"} (""|"f"|"F")
my thoughts for double are the same, just d and D

my concerns are if something fucked up like
.eF
shows up. by my syntax i think i'm accepting the above line as a float literal.
i can't think of a way to demand at least one of the numbers is placed in critical regions based on the various conditions (., e, f) since we can't really look back at previous instances of numbers and make judgements on that as far as i know

**Comment by tjsg1992** [comment]
Definitely a really good start. Quick question, what is the difference between ("1"-"9") and {"1"-"9"} ?

**Comment by tjsg1992** [comment]
Oh! Figured it out, I think. {a} seems to indicate 0 to many, i.e. {a} = (a)*

**Comment by tjsg1992** [comment]
So right now, I don't think something like .eF would be allowed, since your current regular expression requires at least one integer between 1 and 9 to the left of the dot.

On the other hand, something like 0.5 is also not allowed for the same reason, which I think is a problem.

**Comment by tjsg1992** [comment]
FLOAT_LITERAL ::= "0" |    (  ( ("1"-"9") {"0"-"9"} (""|".")  ) | "0." | "."  )  {"0"-"9"}  ("" |  ("e"|"E")  ("1"-"9") {"0"-"9"}   )  (""|"f"|"F")

would be a couple steps closer, I think. Although now things like .eF are accepted.

**Comment by tjsg1992** [comment]
FLOAT_LITERAL ::= "0" |   ( ("1"-"9") {"0"-"9"} ("" | "f" | F) )   |   ( ("1"-"9"){"0"-"9"} ("" | ".") | "0.")   {"0"-"9"}  ("" | ("e"|"E") ("1"-"9") {"1"-"9"})  ("f"|"F")  )

should be even closer. I can't immediately find anything wrong with this one.

**Comment by cresse** [comment]
i don't think there's any way around it but damn this shit is getting hard to read and track.

the second instance of  ("1"-"9") {"0"-"9"}, where it can potentially include the period - could you explain that bit to me? wouldn't those numbers be taken care of in the first instance of  ("1"-"9") {"0"-"9"} ?

otherwise the parentheses, despite being visually awful, seem logically very clean. ty.

my guess is that
float test = 3f;
is read as a float literal first because nothing else includes an f like that, meaning it doesn't have to be converted afterwards. but i don't know how that transcribing process works or where it's located so i can't be sure.

**Comment by tjsg1992** [comment]
That's actually a pretty good point. I think that's vestigial from when I was still trying to figure out when you have to include f or F (which I thought was optional, but is actually always)

**Comment by tjsg1992** [comment]
FLOAT_LITERAL ::= ("0" |  ( ("1"-"9"){"0"-"9"} ("" | ".") | "0.") {"0"-"9"} ("" | ("e"|"E") {"0"-"9"}) ) ("f"|"F")

which I think is now fixed by that.

**Comment by cresse** [comment]
seems good to me! as far as i know all of that applies to double too so that's another one slammed out :+1:

**Comment by tjsg1992** [comment]
As a note, double will differ slightly. Double literals do not need the d at the end unless they would be interpreted as an integer literal otherwise (i.e. 3d). Something like 3.5 is read as a double literal automatically.

**Comment by tjsg1992** [comment]
So something like...
DOUBLE_LITERAL ::= (("0" | ("1-"9"){"0"-"9"}) ("d"|"D")) | (  ("0" | ("1"-"9"){"0"-"9"})   ("." {"0"-"9"} ("" | (("e" | "E") ("0"-"9") {"0"-"9"})) | (("" | "." {"0"-"9"}) ("e" | "E") ("0"-"9") {"0" - "9"})) ("" | "d" | "D"))

**Comment by tjsg1992** [comment]
For 2.14, other literals include:
true, false, Strings, char, and floats, since shorts and bytes are always coerced from integer literals.

2.15, other integer representations include:
binary, hexadecimal, octal

Can anybody think of any others we need to do?

**Comment by cresse** [comment]
we forgot really tiny numbers in scientific notation like 1.2e-35f
adding in ("" | "-" ) after each ("e" | "E"):

DOUBLE_LITERAL ::= (("0" | ("1-"9"){"0"-"9"}) ("d"|"D")) | ( ("0" | ("1"-"9"){"0"-"9"}) ("." {"0"-"9"} ("" | (("e" | "E") ("" | "-" ) ("0"-"9") {"0"-"9"})) | (("" | "." {"0"-"9"}) ("e" | "E") ("" | "-" ) ("0"-"9") {"0" - "9"})) ("" | "d" | "D"))

FLOAT_LITERAL ::= ("0" | ( ("1"-"9"){"0"-"9"} ("" | ".") | "0.") {"0"-"9"} ("" | ("e"|"E") ("" | "-" ) ("0"-"9") {"0"-"9"}) ) ("f"|"F")

**Comment by tjsg1992** [comment]
We also forgot negative numbers in general, e.g. -5, -3.4, etc. lmao

**Comment by cresse** [comment]
oh. excellent point :sob:

re: 2.14 other literals - are true/false already handled by scanner.java? i see
`[line 106 reserved.put(TRUE.image(), TRUE);](https://github.com/tjsg1992/Compiler-Project/blob/operators/src/jminusminus/Scanner.java#L106)`

**Comment by tjsg1992** [comment]
Yeah, they may very well be. I think they're considered reserved words. Good catch!

**Comment by cresse** [comment]
i just had a weird idea. is the number after the e | E actually part of the float? or is it an int that's used to provide additional information about the float like
<regular floatnum> e <int for info> f,
and the e and f are used as beginnings and ends of a marker for recognizing ints there or something
this is just me thinking out loud and clogging up this thread tho. i'm tired :coffee:

**Comment by tjsg1992** [comment]
Yeah, I'm pretty sure it's all included as a single literal. So the scanner is supposed to see the whole thing, go "oh you're a float" and then put the whole thing somewhere else.

Also, slight problem. I'm noticing now that something like ".5" wouldn't be compilable. Ugh.

**Comment by tjsg1992** [comment]
FLOAT_LITERAL ::= ("" | "-") ("0" | ( ("1"-"9"){"0"-"9"} ("" | ".") | "0." | ".") {"0"-"9"} ("" | ("e"|"E") ("" | "-" ) ("0"-"9") {"0"-"9"}) ) ("f"|"F")

should take care of all that for floats. Doubles will be a bit harder.

**Comment by tjsg1992** [comment]
DOUBLE_LITERAL ::= ("" | "-") (("0" | ("1-"9"){"0"-"9"}) ("d"|"D")) | ((("0" | ("1"-"9"){"0"-"9"}) ("." {"0"-"9"} ("" | (("e" | "E") ("" | "-" ) ("0"-"9") {"0"-"9"})) | (("" | "." {"0"-"9"}) ("e" | "E") ("" | "-" ) ("0"-"9") {"0" - "9"})) | ("." ("0"-"9") {"0"-"9} ("" | ("e" | "E") ("0"-"9") {"0"-"9"})))  ("" | "d" | "D"))

I think!

**Comment by cresse** [comment]
STRING_LITERAL ::= "\"" {ESC | ~("\""|"\\"|"\n"|"\r")} {" "} {"!"} {"#-"~"} "\""
CHAR_LITERAL ::= "'" (ESC | ~("'"|"\n"|"\r"|"\\")) (" ") ("!") ("#-"~") "'"

**Comment by tjsg1992** [comment]
I'm going to be working on 2.13-2.15 for a bit, anything that concerns numerical literals. This means I won't be touching strings or char stuff.

**Comment by tjsg1992** [comment]
Actually, it might be best to finish work on Robert's operators branch so that we don't run into crazy merge conflicts.

**Comment by tjsg1992** [comment]
Octal isn't even an actual Java integer representation. >=(

**Comment by tjsg1992** [comment]
Just about done with 2.13 - 2.15. Just need to poke at the actual Java implementation to see when invalid binary sequences (e.g. 0b1013) are detected.

**Comment by tjsg1992** [comment]
BADA-BOOM.
